Revert "Metadata Dialog" (#5149)
Reverts datacommonsorg/website#5147

Hey @nick-next - it looks like this PR was causing some compile issues
for another one of our services. I'm reverting for now - can you take a
look at these errors when running:

```
$ cd static
$ npm run dev:nodemon

```

Output:

```
[nodemon] starting `ts-node src/server.ts`
objc[21881]: Class GNotificationCenterDelegate is implemented in both /opt/homebrew/Cellar/glib/2.84.1/lib/libgio-2.0.0.dylib (0x126d2c648) and /Users/calinc/datcom-website/static/node_modules/sharp/vendor/8.14.5/darwin-arm64v8/lib/libvips-cpp.42.dylib (0x133a51a40). This may cause spurious casting failures and mysterious crashes. One of the duplicates must be removed or renamed.
/Users/calinc/datcom-website/static/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
js/components/elements/button/button.tsx(176,13): error TS2339: Property 'typography' does not exist on type 'Theme'.
js/components/elements/button/button.tsx(177,13): error TS2339: Property 'radius' does not exist on type 'Theme'.
js/components/elements/button/button.tsx(184,18): error TS2339: Property 'spacing' does not exist on type 'Theme'.
js/components/elements/button/button.tsx(199,15): error TS2339: Property 'button' does not exist on type 'Theme'.
js/components/elements/button/button.tsx(200,15): error TS2339: Property 'typography' does not exist on type 'Theme'.
js/components/elements/button/button.tsx(204,15): error TS2339: Property 'button' does not exist on type 'Theme'.
js/components/elements/button/button.tsx(205,15): error TS2339: Property 'typography' does not exist on type 'Theme'.
js/components/elements/button/button.tsx(209,15): error TS2339: Property 'button' does not exist on type 'Theme'.
js/components/elements/button/button.tsx(210,15): error TS2339: Property 'typography' does not exist on type 'Theme'.
js/components/elements/button/button.tsx(217,15): error TS2339: Property 'button' does not exist on type 'Theme'.
js/components/elements/button/button.tsx(220,15): error TS2339: Property 'button' does not exist on type 'Theme'.
js/components/elements/button/button.tsx(223,15): error TS2339: Property 'button' does not exist on type 'Theme'.

    at createTSError (/Users/calinc/datcom-website/static/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/Users/calinc/datcom-website/static/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/Users/calinc/datcom-website/static/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/Users/calinc/datcom-website/static/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/Users/calinc/datcom-website/static/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Object.require.extensions.<computed> [as .tsx] (/Users/calinc/datcom-website/static/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19) {
  diagnosticCodes: [
    2339, 2339, 2339,
    2339, 2339, 2339,
    2339, 2339, 2339,
    2339, 2339, 2339
  ]
}
```