[Webdriver Tests] De-flake Map Test (#5642)
This PR De-flakes map tool webdriver tests with the following changes:

(1) Fix "stale element" failures

On Cloud Run, the map tool webdriver tests sometimes fail with:

```
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
```

This PR de-flakes the test by cleaning up "find element" steps so that
they don't rely on a previously stored element that could go stale while
the tests run.

(2) Increase timeout on a slow-to-load chart